window.DATA = {
  causes: [
    { id: 'R11', parent: 'R1', baseline: 0.8, label: 'Misconfiguration' },
    { id: 'R12', parent: 'R1', baseline: 0.9, label: 'App failure (bug, corruption)' },
    { id: 'R13', parent: 'R1', baseline: 0.8, label: 'Connectivity (wifi)' },
    { id: 'R22', parent: 'R2', baseline: 0.9, label: 'Controller hardware failure' },
    { id: 'R23', parent: 'R2', baseline: 0.8, label: 'Controller firmware / config' },
    { id: 'R31', parent: 'R3', baseline: 1.2, label: 'Relay wiring fault' },
    { id: 'R41', parent: 'R4', baseline: 1.3, label: 'Pump suction-side fault' },
    { id: 'R42', parent: 'R4', baseline: 1.1, label: 'Pump hardware failure' },
    { id: 'R51', parent: 'R5', baseline: 1.2, label: 'Main hose 32mm leak / break' },
    { id: 'R52', parent: 'R5', baseline: 0.8, label: 'Main hose 32mm air / debris clog' },
    { id: 'R61', parent: 'R6', baseline: 1.2, label: 'Per-zone hot conductor fault' },
    { id: 'R62', parent: 'R6', baseline: 1.4, label: 'Common wire fault' },
    { id: 'R63', parent: 'R6', baseline: 0.8, label: 'Wire-to-triac connection fault' },
    { id: 'R71', parent: 'R7', baseline: 1.2, label: 'Solenoid failure' },
    { id: 'R72', parent: 'R7', baseline: 1.4, label: 'Diaphragm failure' },
    { id: 'R73', parent: 'R7', baseline: 0.7, label: 'Valve body / seal failure' },
    { id: 'R74', parent: 'R7', baseline: 0.8, label: 'Valve misconfiguration' },
    { id: 'R81', parent: 'R8', baseline: 1.1, label: 'Zone hoses 25mm / fitting damage' },
    { id: 'R82', parent: 'R8', baseline: 0.9, label: 'Zone hoses 25mm air / debris clog' },
    { id: 'R91', parent: 'R9', baseline: 1.1, label: 'Sprinkler debris / nozzle' },
    {
      id: 'R92',
      parent: 'R9',
      baseline: 1.0,
      label: 'Sprinkler misconfigured (manual shutoff, arc/radius)',
    },
  ],
  questions: [
    {
      id: 'A1',
      stage: 1,
      group: 'Component ages',
      text: 'Age of pump',
      options: [
        { label: '0–4 yrs', effects: { R4: -0.2 } },
        { label: '4–8 yrs', effects: {} },
        { label: '8–12 yrs', effects: { R4: 0.2 } },
        { label: '12+ yrs', effects: { R4: 0.4 } },
      ],
    },
    {
      id: 'A2',
      stage: 1,
      group: 'Component ages',
      text: 'Age of valves (no replacements)',
      options: [
        { label: '0–4 yrs', effects: { R71: -0.2, R72: -0.2, R73: -0.2 } },
        { label: '4–8 yrs', effects: { R71: 0.2, R72: 0.2, R73: 0.2 } },
        { label: '8–12 yrs', effects: { R71: 0.2, R72: 0.2, R73: 0.2 } },
        { label: '12+ yrs', effects: { R71: 0.4, R72: 0.4, R73: 0.4 } },
      ],
    },
    {
      id: 'A3',
      stage: 1,
      group: 'Component ages',
      text: 'Age of pump start relay',
      options: [
        { label: '0–4 yrs', effects: { R3: -0.2 } },
        { label: '4–8 yrs', effects: {} },
        { label: '8–12 yrs', effects: { R3: 0.2 } },
        { label: '12+ yrs', effects: { R3: 0.4 } },
      ],
    },
    {
      id: 'A4',
      stage: 1,
      group: 'Component ages',
      text: 'Age of controller',
      options: [
        { label: '0–4 yrs', effects: { R12: -0.2, R22: -0.2, R23: -0.2 } },
        { label: '4–8 yrs', effects: {} },
        { label: '8–12 yrs', effects: { R12: 0.2, R22: 0.2, R23: 0.2 } },
        { label: '12+ yrs', effects: { R12: 0.4, R22: 0.4, R23: 0.4 } },
      ],
    },
    {
      id: 'A5',
      stage: 1,
      group: 'Component ages',
      text: 'Age of rotors / sprinklers',
      options: [
        { label: '0–4 yrs', effects: { R91: -0.2, R92: -0.12 } },
        { label: '4–8 yrs', effects: {} },
        { label: '8–12 yrs', effects: { R91: 0.2, R92: 0.12 } },
        { label: '12+ yrs', effects: { R91: 0.4, R92: 0.24 } },
      ],
    },

    {
      id: 'Q1',
      stage: 2,
      group: 'Symptoms',
      text: 'Scope of failure?',
      options: [
        {
          label: 'All zones fail',
          effects: { R1: 0.2, R2: 0.2, R3: 0.2, R4: 0.2, R5: 0.2 },
        },
        { label: 'Multiple zones (not all)', effects: { R5: 0.2, R62: 0.2, R4: 0.2 } },
        { label: 'Single zone', effects: { R61: 0.2, R63: 0.2, R7: 0.2, R8: 0.2 } },
        { label: 'One sprinkler', effects: { R9: 2 } },
      ],
    },
    {
      id: 'Q2',
      stage: 2,
      group: 'Symptoms',
      text: 'Same interface, same issue?',
      options: [
        { label: 'Manual works, app has issues', effects: { R11: 2, R13: 2 } },
        {
          label: 'Yes — nothing starts at all',
          effects: { R2: 0.2, R3: 0.2, R63: 0.2 },
        },
        {
          label: 'Yes — both start something',
          effects: { R4: 0.2, R5: 0.2, R7: 0.2, R8: 0.2, R9: 0.2 },
        },
      ],
    },
    {
      id: 'Q3',
      stage: 2,
      group: 'Symptoms',
      text: 'How does water leave rotors?',
      options: [
        {
          label: 'No water',
          effects: { R1: 0.6, R2: 0.6, R31: 0.6, R42: 0.6, R6: 0.6, R71: 0.6 },
        },
        {
          label: 'Weak',
          effects: {
            R41: 0.2,
            R42: 0.2,
            R52: 0.2,
            R6: 0.2,
            R72: 0.2,
            R74: 0.2,
            R82: 0.2,
            R91: 0.2,
            R92: 0.2,
          },
        },
        { label: 'Strong, then weak', effects: { R41: 0.6, R42: 0.6 } },
        { label: 'Weak, then strong', effects: { R52: 0.4, R82: 0.4, R41: 0.4 } },
        { label: 'Pressure fluctuates', effects: { R41: 0.2, R42: 0.2, R52: 0.2 } },
        {
          label: 'Erratic, no pattern',
          effects: {
            R11: 0.4,
            R12: 0.4,
            R13: 0.4,
            R23: 0.4,
            R61: 0.4,
            R62: 0.4,
            R63: 0.4,
            R71: 0.4,
          },
        },
        {
          label: 'Leaks when system is off',
          effects: { R72: 0.4, R73: 0.4, R74: 0.4, R51: 0.4, R81: 0.4 },
        },
        { label: 'Geyser-like pressure', effects: { R51: 0.4, R81: 0.4, R91: 0.4 } },
        {
          label: 'Normal',
          effects: {
            R1: 0.6,
            R4: -0.4,
            R5: -0.4,
            R6: -0.4,
            R7: -0.4,
            R8: -0.4,
            R9: -0.4,
          },
        },
      ],
    },
    {
      id: 'Q4',
      stage: 2,
      group: 'Symptoms',
      text: 'Do you hear the pump start?',
      options: [
        {
          label: 'Pump runs',
          effects: { R4: 0.2, R5: 0.2, R6: 0.2, R7: 0.2, R8: 0.2, R9: 0.2 },
        },
        { label: 'Pump silent / hums', effects: { R31: 1, R42: 1, R1: 1, R2: 1 } },
      ],
    },
    {
      id: 'Q5',
      stage: 2,
      group: 'Symptoms',
      text: 'If pump runs, does manual hose work?',
      options: [
        {
          label: 'Strong, steady',
          effects: { R5: 0.4, R6: 0.4, R7: 0.4, R8: 0.4, R9: 0.4 },
        },
        { label: 'Weak / sputtering / air-laden', effects: { R41: 0.2 } },
        { label: 'None at all', effects: { R41: 0.6, R42: 0.6 } },
      ],
    },
    {
      id: 'Q6',
      stage: 2,
      group: 'Symptoms',
      text: 'Pump behavior on start?',
      options: [
        { label: 'Starts smoothly, builds pressure', effects: { R42: -0.5 } },
        {
          label: "Starts but won't build pressure",
          effects: { R41: 0.6, R51: 0.6, R42: 0.6 },
        },
        { label: "Hums / trips / won't start", effects: { R42: 1, R31: 1 } },
        { label: 'Short-cycles on/off', effects: { R51: 0.4, R41: 0.4, R42: 0.4 } },
      ],
    },
    {
      id: 'Q7',
      stage: 2,
      group: 'Symptoms',
      text: 'Do you see water / wet ground?',
      options: [
        { label: 'Along the main line route', effects: { R51: 2 } },
        { label: 'Around a valve box', effects: { R73: 2, R74: 2 } },
        { label: 'Along zone lines', effects: { R81: 2 } },
        {
          label: 'Nothing visible',
          effects: { R51: -0.6, R73: -0.6, R74: -0.6, R81: -0.6 },
        },
      ],
    },
    {
      id: 'Q8',
      stage: 2,
      group: 'Symptoms',
      text: 'What do you hear when valve activates?',
      options: [
        { label: 'Clear click', effects: { R72: 0.4, R8: 0.4, R91: 0.4, R92: 0.6 } },
        { label: 'Buzz / hum, no click', effects: { R71: 1, R6: 1 } },
        {
          label: 'Weak click',
          effects: { R61: 0.2, R62: 0.2, R63: 0.2, R71: 0.2 },
        },
        { label: 'Silent', effects: { R61: 1, R62: 1, R63: 1, R71: 1 } },
      ],
    },
    {
      id: 'Q9',
      stage: 2,
      group: 'Symptoms',
      text: 'Manually open valve at solenoid does zone run correctly?',
      options: [
        { label: 'Yes, zone runs', effects: { R6: 0.6, R71: 0.6 } },
        {
          label: 'No flow even manually',
          effects: { R72: 0.6, R73: 0.6, R8: 0.6, R5: 0.6 },
        },
      ],
    },
    {
      id: 'Q11',
      stage: 2,
      group: 'Symptoms',
      text: 'How did the problem progress?',
      options: [
        {
          label: 'Sudden, every time since',
          effects: {
            R22: 0.2,
            R31: 0.2,
            R51: 0.2,
            R63: 0.2,
            R71: 0.2,
            R92: 0.3,
          },
        },
        {
          label: 'Sudden, intermittent since',
          effects: { R13: 0.2, R61: 0.2, R62: 0.2, R71: 0.2 },
        },
        {
          label: 'Gradual, now every time',
          effects: { R4: 0.4, R72: 0.4, R73: 0.4, R91: 0.4, R92: 0.12, R52: 0.4 },
        },
        { label: 'Gradual, still intermittent', effects: { R4: 0.2, R7: 0.2, R6: 0.2 } },
        { label: 'Intermittent from start', effects: { R11: 0.2, R6: 0.2 } },
        {
          label: 'Sometimes, no pattern',
          effects: { R13: 0.2, R61: 0.2, R62: 0.2, R42: 0.2 },
        },
      ],
    },
    {
      id: 'Q12',
      stage: 2,
      group: 'Symptoms',
      text: 'Zone behavior over the run cycle?',
      options: [
        { label: 'Strong at start, fades', effects: { R52: 0.4, R82: 0.4, R41: 0.4 } },
        { label: 'Weak start to finish', effects: { R4: 0.2, R72: 0.2, R81: 0.2 } },
        { label: 'Fine until late, then drops', effects: { R42: 0.4, R71: 0.4 } },
        { label: 'Surges / hammers', effects: { R52: 0.4 } },
        { label: 'Same level throughout', effects: {} },
      ],
    },
    {
      id: 'Q13a',
      stage: 2,
      group: 'Symptoms',
      text: 'Did restarting the controller help?',
      options: [
        { label: 'Briefly fixed', effects: { R12: 0.6, R13: 0.6, R23: 0.6 } },
        { label: 'No effect', effects: { R1: -0.2, R2: -0.2 } },
      ],
    },
    {
      id: 'Q13b',
      stage: 2,
      group: 'Symptoms',
      text: 'Did restarting the pump help?',
      options: [
        { label: 'Briefly fixed', effects: { R42: 0.4, R31: 0.4 } },
        { label: 'No effect', effects: { R42: -0.2 } },
      ],
    },

    {
      id: 'E_service',
      stage: 3,
      type: 'matrix',
      group: 'Events',
      text: 'Recent service or work — for each, how did the issue relate to it?',
      columns: [
        { id: 'no', label: 'N/A', mult: 0.0 },
        { id: 'right', label: 'Started right after', mult: 1.0 },
        { id: 'days', label: 'Started week(s) after', mult: 0.6 },
        { id: 'worse', label: 'Worsened (same)', mult: 0.0 },
        { id: 'faster', label: 'Worsened (faster)', mult: 0.4 },
        { id: 'briefly', label: 'Briefly fixed, returned', mult: 0.2 },
      ],
      rows: [
        { id: 'pump', label: 'Pump ', effects: { R4: 1 } },
        { id: 'relay', label: 'Pump-start-relay ', effects: { R3: 1 } },
        {
          id: 'ctrl',
          label: 'Controller ',
          effects: { R11: 1, R22: 1 },
        },
        { id: 'app', label: 'App / wifi / settings change', effects: { R1: 1 } },
        { id: 'valves', label: 'Valve ', effects: { R7: 1 } },
        {
          id: 'spr',
          label: 'Sprinkler ',
          effects: { R91: 0.6, R92: 1.0 },
        },
        { id: 'zhose', label: 'Zone hose / fittings ', effects: { R8: 1, R5: 1 } },
        { id: 'wiring', label: 'System wiring ', effects: { R6: 1 } },
      ],
    },
    {
      id: 'E_external',
      stage: 3,
      type: 'matrix',
      group: 'Events',
      text: 'External events — for each, how did the issue relate to it?',
      columns: [
        { id: 'no', label: 'N/A', mult: 0.0 },
        { id: 'right', label: 'Started right after', mult: 1.0 },
        { id: 'days', label: 'Started week(s) after', mult: 0.6 },
        { id: 'worse', label: 'Worsened (same)', mult: 0.0 },
        { id: 'faster', label: 'Worsened (faster)', mult: 0.4 },
        { id: 'briefly', label: 'Briefly fixed, returned', mult: 0.2 },
      ],
      rows: [
        {
          id: 'storm',
          label: 'Storm / lightning',
          effects: { R22: 1, R6: 1, R12: 1 },
        },
        {
          id: 'freeze',
          label: 'Freeze',
          effects: { R51: 1, R73: 1, R81: 1 },
          drainable: true,
        },
        { id: 'heat', label: 'Heatwave / drought', effects: { R41: 1 } },
        { id: 'outage', label: 'Power outage', effects: { R12: 1, R23: 1 } },
        { id: 'pests', label: 'Pests / rodents', effects: { R51: 1, R81: 1, R6: 1 } },
        {
          id: 'dig',
          label: 'Digging / vehicle',
          effects: { R51: 1, R61: 1, R62: 1, R81: 1 },
        },
      ],
    },

    {
      id: 'D1',
      stage: 4,
      group: 'Hard tests',
      text: 'Flow meter reads 1.0–3.0?',
      options: [
        { label: 'Yes (in range)', effects: { R4: -0.4, R5: -0.4 } },
        { label: 'No (out of range)', effects: { R4: 0.2, R5: 0.2 } },
      ],
    },
    {
      id: 'D2',
      stage: 4,
      group: 'Hard tests',
      text: 'Multimeter at zone terminal during call (~24 VAC zone-to-common)?',
      options: [
        { label: '~24 VAC present', effects: { R7: 0.4, R22: -0.4, R6: -0.4 } },
        { label: '0 V', effects: { R22: 0.6, R63: 0.6, R11: 0.6 } },
        { label: 'Low / fluctuating', effects: { R61: 0.6, R62: 0.6 } },
      ],
    },
    {
      id: 'D3',
      stage: 4,
      group: 'Hard tests',
      text: 'Mains voltage at controller outlet?',
      options: [
        { label: 'Normal (~230 VAC)', effects: { R22: -0.4 } },
        { label: 'Low or absent', effects: { R22: 1.6 } },
        { label: 'Present but controller dead', effects: { R22: 1.6 } },
      ],
    },
    {
      id: 'D4',
      stage: 4,
      group: 'Hard tests',
      text: 'Solenoid coil resistance (typical 20–60 Ω)?',
      options: [
        { label: 'In range', effects: { R71: -0.4, R72: 0.2, R73: 0.2, R74: 0.2 } },
        { label: 'Open / infinite', effects: { R71: 1.6 } },
        { label: 'Near zero / very low', effects: { R71: 1.6 } },
        { label: 'Fine at coil, bad at controller', effects: { R61: 1.6 } },
      ],
    },
    {
      id: 'D5',
      stage: 4,
      group: 'Hard tests',
      text: 'Common-wire continuity controller→valves?',
      options: [
        { label: 'Continuous, low resistance', effects: { R62: -0.4 } },
        { label: 'Open or high resistance', effects: { R62: 1.6 } },
        { label: 'Intermittent when wiggled', effects: { R62: 0.6 } },
      ],
    },
    {
      id: 'D6',
      stage: 4,
      group: 'Hard tests',
      text: '24 VAC at controller pump/master terminal during call?',
      options: [
        { label: '~24 VAC, relay does not pull in', effects: { R31: 0.6 } },
        { label: '0 V', effects: { R22: 0.6, R11: 0.6 } },
        { label: 'Voltage present, relay clicks, no 230V', effects: { R31: 0.6 } },
      ],
    },
    {
      id: 'D7',
      stage: 4,
      group: 'Hard tests',
      text: 'Controller board visual check?',
      options: [
        { label: 'Looks fine', effects: { R22: -0.2 } },
        { label: 'Not fine (corrosion, burn marks)', effects: { R22: 1 } },
      ],
    },
    {
      id: 'D8',
      stage: 4,
      group: 'Hard tests',
      text: 'Dig & inspect hoses for damage?',
      options: [
        { label: 'Damage found', effects: { R51: 1, R81: 1 } },
        { label: 'No damage', effects: { R51: -0.4, R81: -0.4 } },
      ],
    },
    {
      id: 'D9',
      stage: 4,
      group: 'Hard tests',
      text: 'Open each valve and inspect internals?',
      options: [
        { label: 'Intact, no debris', effects: { R72: -0.4, R73: -0.4 } },
        { label: 'Damaged or debris', effects: { R72: 1, R73: 0.6 } },
      ],
    },
    {
      id: 'D10',
      stage: 4,
      group: 'Hard tests',
      text: 'Swap suspect valve with known-good — does problem stay with the zone?',
      options: [
        { label: 'Yes (stays with zone)', effects: { R7: -0.6, R6: 0.6, R8: 0.6 } },
        { label: 'No (follows the valve)', effects: { R7: 1.6 } },
      ],
    },
  ],
};
